
.. _Supported Image Extensions:
   https://docs.blender.org/manual/en/latest/files/media/image_formats.html#image-formats

.. _bpy_prop_collection:
    https://docs.blender.org/api/current/bpy.types.bpy_prop_collection

.. _Object:
    https://docs.blender.org/api/current/bpy.types.Object.html#bpy.types.Object

.. _WindowManager:
    https://docs.blender.org/api/current/bpy.types.WindowManager.html#bpy.types.WindowManager

.. _Window:
    https://docs.blender.org/api/current/bpy.types.Window.html#bpy.types.Window

.. _Material:
    https://docs.blender.org/api/current/bpy.types.Material.html#bpy.types.Material

.. _Texture:
    https://docs.blender.org/api/current/bpy.types.Texture.html#bpy.types.Texture

.. _World:
    https://docs.blender.org/api/current/bpy.types.World.html#bpy.types.World

.. _Lamp:
    https://docs.blender.org/api/current/bpy.types.Lamp.html#bpy.types.Lamp

.. _Image:
    https://docs.blender.org/api/current/bpy.types.Image.html#bpy.types.Image

.. _Brush:
    https://docs.blender.org/api/current/bpy.types.Brush.html#bpy.types.Brush

.. _GreasePencil:
    https://docs.blender.org/api/current/bpy.types.GreasePencil.html#bpy.types.GreasePencil

.. _Scene:
    https://docs.blender.org/api/current/bpy.types.Scene.html#bpy.types.Scene

.. _Screen:
    https://docs.blender.org/api/current/bpy.types.Screen.html#bpy.types.Screen

.. _Action:
    https://docs.blender.org/api/current/bpy.types.Action.html#bpy.types.Action

.. _NodeTree:
    https://docs.blender.org/api/current/bpy.types.NodeTree.html#bpy.types.NodeTree

.. _GPUShader:
    https://docs.blender.org/api/current/gpu.types.html#gpu.types.GPUShader

.. _GPUTexture:
    https://docs.blender.org/api/current/gpu.types.html#gpu.types.GPUTexture

.. _GPUOffscreen:
    https://docs.blender.org/api/current/gpu.types.html#gpu.types.GPUOffscreen

.. _EnumProperty:
    https://docs.blender.org/api/current/bpy.props.html#bpy.props.EnumProperty

.. _FloatProperty:
    https://docs.blender.org/api/current/bpy.props.html#bpy.props.FloatProperty

.. _mathutils.Vector:
    https://docs.blender.org/api/current/mathutils.html#mathutils.Vector

.. _Context:
    https://docs.blender.org/api/current/bpy.types.Context.html#bpy.types.Context

.. _UILayout:
    https://docs.blender.org/api/current/bpy.types.UILayout.html#bpy.types.UILayout

.. _Event:
    https://docs.blender.org/api/current/bpy.types.Event.html#bpy.types.Event

.. _Event.type:
    https://docs.blender.org/api/current/bpy.types.Event.html#bpy.types.Event.type

.. _Area:
    https://docs.blender.org/api/current/bpy.types.Area.html#bpy.types.Area

.. _Area.type:
    https://docs.blender.org/api/current/bpy.types.Area.html#bpy.types.Area.type

.. _Space.type:
    https://docs.blender.org/api/current/bpy.types.Space.html#bpy.types.Space.type

.. _Space:
    https://docs.blender.org/api/current/bpy.types.Space.html#bpy.types.Space

.. _Region.type:
    https://docs.blender.org/api/current/bpy.types.Region.html#bpy.types.Region.type

.. _Region.tag_redraw():
    https://docs.blender.org/api/current/bpy.types.Region.html#bpy.types.Region.tag_redraw

.. _Region:
    https://docs.blender.org/api/current/bpy.types.Region.html#bpy.types.Region

.. _AddonPreferences:
    https://docs.blender.org/api/current/bpy.types.AddonPreferences.html#bpy.types.AddonPreferences

.. _ID:
    https://docs.blender.org/api/current/bpy.types.ID.html#bpy.types.ID

.. _GPUBatch:
    https://docs.blender.org/api/current/gpu.types.html#gpu.types.GPUBatch

.. _Vector:
    https://docs.blender.org/api/current/mathutils.html#mathutils.Vector

.. _GPUShaderCreateInfo:
    https://docs.blender.org/api/current/gpu.types.html#gpu.types.GPUShaderCreateInfo

.. _GPUFrameBuffer:
    https://docs.blender.org/api/current/gpu.types.html#gpu.types.GPUFrameBuffer