name: Publish to PyPI on version tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'          # e.g. 1.2.3
      - '[0-9]+.[0-9]+.[0-9]+a[0-9]+'   # e.g. 1.2.3a1
      - '[0-9]+.[0-9]+.[0-9]+b[0-9]+'   # e.g. 1.2.3b1
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'  # e.g. 1.2.3rc1
      - '[0-9]+.[0-9]+.[0-9]+.post[0-9]+' # e.g. 1.2.3.post1
      - '[0-9]+.[0-9]+.[0-9]+.dev[0-9]+'  # e.g. 1.2.3.dev1

permissions:
  id-token: write  # Needed for trusted publishing
  contents: read   # For actions/checkout

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # NOTE: For test Pypi
        # with:
        #   repository-url: https://test.pypi.org/legacy/
